name: Build and Push Docker Images to ECR

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: latest

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push MySQL image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: mysql-repo
        run: |
          echo "Building MySQL image..."
          docker build -t $ECR_REGISTRY/$REPO:$IMAGE_TAG -f Dockerfile_mysql .
          docker push $ECR_REGISTRY/$REPO:$IMAGE_TAG

      - name: Build and push Web App image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: webapp-repo
        run: |
          echo "Building Web App image..."
          docker build -t $ECR_REGISTRY/$REPO:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$REPO:$IMAGE_TAG
